Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  IamRole:
    Type: String
    Default: SikandarCWAgentRole
  InstanceType:
    Description: Webserver EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large

Mappings:
  Settings:
    MySQL:
      Engine: MySQL
      Version: '5.7'

  RegionMap: 
    us-east-1: 
      "HVM64": "ami-0756fbca465a59a30"
    us-east-2:
      "HVM64": "ami-04768381bf606e2b3"
    us-west-1: 
      "HVM64": "ami-063dd30adbb186909"
    eu-west-2: 
      "HVM64": "ami-07a0c6e669965bb7c"
    ap-south-1:
      "HVM64": "ami-0eacc5b7915ba9921"
    ap-northeast-2:
      "HVM64": "ami-082b5ca9ff663f3b8"
    ap-southeast-1: 
      "HVM64": "ami-03097abf0db1cdff2"
    ap-southeast-2:
      "HVM64": "ami-05067171f4230ac41"
    ap-northeast-1: 
      "HVM64": "ami-0ccdbc8c1cb7957be"
    ca-central-1:
      "HVM64": "ami-07ab3281411d31d04"
    eu-central-1:
      "HVM64": "ami-03a71cec707bfc3d7"
    eu-west-1:
      "HVM64": "ami-03c242f4af81b2365"
    eu-west-2:
      "HVM64": "ami-05663d374a152d239"
    eu-west-3:
      "HVM64": "ami-0f962299dc4d90c81"
    eu-north-1:
      "HVM64": "ami-be4bc3c0"
    sa-east-1:
      "HVM64": "ami-0eb2a191bf5e40e10"


Resources:
  Webserver:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        !Ref InstanceType
      SecurityGroupIds: 
        - !ImportValue sikandarStack-PublicSecurityGroup
      KeyName:
        !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      SubnetId: 
        Fn::ImportValue: sikandarStack-Subnet
      IamInstanceProfile: !Ref IamRole
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          sleep 90
          yum install deltarpm -y
          yum update -y
          yum upgrade -y
          yum install php-mysql -y
          yum mysql-server -y 
          yum httpd -y
          yum php -y
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v -s ${AWS::StackName} -r Webserver -c Install --region ${AWS::Region}
          service httpd start
          cd /var/www/html
          echo "Hello World" >> index.html
          cd ~
          mkdir tempcloudwatch
          cd tempcloudwatch
          wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
          rpm -U ./amazon-cloudwatch-agent.rpm
          wget https://s3.amazonaws.com/alamhtml/cloudwatchagent-linux-config.json
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:cloudwatchagent-linux-config.json -s
      Tags:
        - Key: Name
          Value: SikandarInstance
Outputs:
  Webserver:
    Value: !Ref Webserver
    Export:
      Name: !Sub "sikandarStack-Webserver"
 
  KeyName:
    Value: !Ref KeyName
    Export:
      Name: !Sub "sikandarStack-KeyName"

  InstanceType:
    Value: !Ref InstanceType
    Export:
      Name: SikandarStack-InstanceType