Parameters:
  instanceid:
    Description: "Choose an instance id"
    Type: AWS::EC2::Instance::Id

  instancename:
    Description: "Please provide EC2 instance name"
    Type: "String"
    MinLength: '1'
    MaxLength: '50'
Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: sqs
        Endpoint: !GetAtt [SQSQueue, Arn]
  AllowSNS2SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref 'SQSQueue']
      PolicyDocument:
        Version: '2008-10-17'
        Id: PublicationPolicy
        Statement:
        - Sid: Allow-SNS-SendMessage
          Effect: Allow
          Principal:
            AWS: '*'
          Action: ['sqs:*']
          Resource: !GetAtt [SQSQueue, Arn]
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref 'SNSTopic'

  CPUAlarmCRITICAL: 
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain 
    Properties:
      AlarmDescription: !Sub "${instancename} - ${instanceid} - High CPU Usage 95%"
      AlarmActions:
      - !Ref SNSTopic
      OKActions:
      - !Ref SNSTopic
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '900' 
      EvaluationPeriods: '2'
      Threshold: '95'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref instanceid

  SystemStatusAlarmCRITICAL:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    Properties:
      AlarmDescription: !Sub "${instancename} - ${instanceid} - instance recovery process"
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: '60'
      EvaluationPeriods: '2'
      ComparisonOperator: GreaterThanThreshold
      Threshold: '0'
      AlarmActions:
      - !Sub "arn:aws:automate:${AWS::Region}:ec2:recover"
      - !Ref SNSTopic
      OKActions:
      - !Ref SNSTopic
      Dimensions:
      - Name: InstanceId
        Value: !Ref instanceid

  InstanceStatusAlarmCRITICAL: 
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Retain
    Properties:
      AlarmDescription: !Sub "${instancename} - ${instanceid} - Instance Status Check Failed - please investigate. Troubleshooting: https://goo.gl/Ea27Gd"
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_Instance
      Statistic: Minimum
      Period: '60'
      EvaluationPeriods: '3'
      ComparisonOperator: GreaterThanThreshold
      Threshold: '0'
      AlarmActions:
      - !Ref SNSTopic
      OKActions:
      - !Ref SNSTopic
      Dimensions:
      - Name: InstanceId
        Value: !Ref instanceid

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: detect-instance-changes
      Description: A CloudWatch Event Rule that detects any changes to EC2 Instance service.
      State: ENABLED
      Targets:
        - Arn:
            Ref: SNSTopic
          Id: target-id1
      EventPattern:
        source:
          - aws.ec2

Outputs:
  QueueArn:
    Value: !GetAtt [SQSQueue, Arn]
    Description: ARN of SQS Queue
    Export:
      Name: !Sub "QueueARN" 
  TopicArn:
    Value: !Ref SNSTopic
    Description: ARN of SNS Topic

